### ISSUE TITLE
Auto refresh mirror when config json gets updated :D

### ISSUE THREAD

**Issue by vannio** [vannio/makers-mirror#6]
With browsersync?

**Comment by andreamazza89** [comment]
Was wondering about that: we need to effectively force a page refresh from the server I guess? Will do some research..

**Comment by vannio** [comment]
Browsersync does the job! I've been testing it out with the node server, but we need to find a way to make it *only* refresh the mirror display (it currently refreshes all damn pages)

**Comment by vannio** [comment]
I think I got it! `npm start` as usual, go to [localhost:3000](http://localhost:3000) to do control panel stuff, and [localhost:3001/mirror](http://localhost:3001/mirror) should auto-reload every time the json file is updated. You can all thank me on Monday ;D
